### ISSUE TITLE
Example with transition

### ISSUE THREAD

**Issue by marcoprodata** [keen-on-design/vue-flash-message#12]
Is possible to provide a example with using transition?

**Comment by doits** [comment]
@marcoprodata simply do this:

```css
.flash__message {
  transition: all 1s;
}

.list-complete-enter,
.list-complete-leave-to {
  opacity: 0;
  transform: translateY(30px);
}

.list-complete-leave-active {
  position: absolute;
}

.list-move {
  transition: transform 1s;
}
```

And use this transition:

```html
<flash-message transition-name="list-complete" />
```

**Comment by keen-on-design** [comment]
You can find working example [here](https://github.com/keen-on-design/vue-flash-message/blob/master/dev/App.vue) in dev sources.
```css
.flashpool {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
  position: fixed;
  top: 20px;
  right: 20px;
  max-height: 400px;
  width: 260px;
  -webkit-perspective: 400px;
          perspective: 400px;
}
.flashpool .flash__message {
  width: 260px;
  -webkit-transition: all 500ms;
  -o-transition: all 500ms;
  transition: all 500ms;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  font-family: 'Oxygen', sans-serif;
  font-size: 13px;
  line-height: 130%;
}
.flash-enter, .flash-leave-to {
  opacity: 0;
  -webkit-transform: rotateX(-30deg) scale(.88) translateY(-30px);
          transform: rotateX(-30deg) scale(.88) translateY(-30px);
}
.flash-leave-active {
  position: absolute;
}
```
an use 
```html
<flash-message transition-name="list-complete" />
```
Or you can refer to @doits comment:)
